version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=newsletter
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=1000'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  app:
    build: .
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - APP_ENVIRONMENT=docker

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  db:


